apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-harness-worker-testing
  namespace: temporal-michaelj-agent-harness-demo
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::429214323166:role/temporal-michaelj-agent-harness-demo-worker-testing
